[package]
name = "bwsm"
version = "0.1.0"
authors = ["Lucas Vogelsang <l@lucasvo.com>"]

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen="0.2"
bellman="0.1.0"
pairing = "0.14"
rand = "0.4"

